//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerDEVApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cola
    {
        public int iColaId { get; set; }
        public string sEstado { get; set; }
        public string sNumCola { get; set; }
        public System.DateTime dtHoraSalida { get; set; }
        public System.DateTime dtHoraLlegada { get; set; }
        public string sEstadoPagado { get; set; }
        public int iPedidoId { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
