//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerDEVApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordenada
    {
        public int iCoordenadaId { get; set; }
        public string sCoordenada_num { get; set; }
        public int iZonaId { get; set; }
    }
}
