//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerDEVApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int iEmpleadoId { get; set; }
        public string sNombre { get; set; }
        public string sApellido { get; set; }
        public string sTelefono { get; set; }
        public string sEmail { get; set; }
        public int iRolId { get; set; }
        public int iUsuarioId { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
