//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerDEVApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int iPedidoId { get; set; }
        public System.DateTime dtPedido { get; set; }
        public string sDescripcion { get; set; }
        public string sTiempoEntrega { get; set; }
        public string sDireccionEntrega { get; set; }
        public string sZona { get; set; }
        public string sCoordenadasX { get; set; }
        public string sCoordenadasY { get; set; }
        public decimal dPrecioTotal { get; set; }
        public decimal dDescuento { get; set; }
        public decimal dRecargos { get; set; }
        public decimal dPrecioNeto { get; set; }
        public int iClienteId { get; set; }
        public int iSucursald { get; set; }
        public int iZonaId { get; set; }
        public int iEmpleadoId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Zona Zona { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
