//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerDEVApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int iProductoId { get; set; }
        public string sNombreProducto { get; set; }
        public string sDescripccion { get; set; }
        public System.DateTime dPrecio { get; set; }
        public string sTipo { get; set; }
        public string sUnidad { get; set; }
        public string sTiempoPreparacion { get; set; }
    }
}
