//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerDEVApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.Empleado = new HashSet<Empleado>();
        }
    
        public int iRolId { get; set; }
        public string sNombreRol { get; set; }
        public string sTurno { get; set; }
    
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}
