//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerDEVApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public int iSucursald { get; set; }
        public string sNombre { get; set; }
        public string sDireccion { get; set; }
        public string sTelefono { get; set; }
        public int iZonaId { get; set; }
    
        public virtual Zona Zona { get; set; }
    }
}
